services:
  scraper:
    image: ghcr.io/arneby/evkollen-public-scraper:latest
    pull_policy: always
    restart: "no"
    environment:
      WORKER_URL: https://evkollen-public-worker.gurka.workers.dev
      WORKER_SECRET: evkollen2026
