name = "evkollen-public-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
account_id = "9470477318f84f079a2849a9bfdb85f1"

[[d1_databases]]
binding = "DB"
database_name = "evkollen-public"
database_id = "547f3070-e483-4ac6-a5a9-94a3d7ab1848"
